#!/usr/bin/env bash
# provisioning/ec2/bringup-ec2.sh
# One-shot bring-up of the CogniForge rack on an EC2 instance.
#
# Designed for a single-node cluster (the instance is both control plane and
# worker). For a multi-node pool run it once per instance:
#   standalone node  : NODE_TIER=tier1 ./bringup-ec2.sh     (infra only)
#   GPU node (24GB)  : NODE_TIER=tier2 ./bringup-ec2.sh
#   GPU node (40GB+) : NODE_TIER=tier3 ./bringup-ec2.sh     (wan21 target)
# The first tier1 brings up RKE2 + Argo; GPU tiers join it and label
# themselves. ECR login uses the node's IAM role (InstanceProfile) so no
# keys are stored on disk.
#
# Required env:
#   REGION        AWS region (default: from metadata/AWS_REGION)
#   REGISTRY      full ECR prefix e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/cogniforge
# Optional env:
#   NODE_TIER     tier1|tier2|tier3 (default tier1; only tier1 installs the server)
#   RKE2_TOKEN    shared cluster token (auto-generated by the tier1 bootstrap)
#   IMAGE_TAG     image tag to deploy (default latest)
#   RACK_ENGINE_URL  base URL the frontend talks to (default http://localhost:8000)
#   GIT_REPO      repo to clone (default: this script's own git remote)
#   SSM_SERVICE   if 1, starts systems-manager agent for 2FA-less SSH
set -euo pipefail

REGION="${REGION:-${AWS_REGION:-}}"
NODE_TIER="${NODE_TIER:-tier1}"
RKE2_TOKEN="${RKE2_TOKEN:-}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
RACK_ENGINE_URL="${RACK_ENGINE_URL:-http://localhost:8000}"
GIT_REPO="${GIT_REPO:-https://github.com/androidcircus/ManifestAI-cogniforge-vx.git}"
RACK_DIR="${RACK_DIR:-/opt/cogniforge-rack}"

if [ -z "$REGION" ]; then
  echo "REGION not set; cannot do ECR login." >&2
  exit 1
fi

log()  { printf '\n==> %s\n' "$*"; }
is_ub() { command -v apt-get >/dev/null 2>&1; }

log "Installing system deps (docker + jq + git; aws CLI if missing)"
if is_ub; then
  sudo apt-get update -y
  sudo apt-get install -y jq git ca-certificates curl
  if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sudo sh
  fi
else
  sudo yum install -y jq git docker
  sudo systemctl enable docker --now || true
fi
sudo usermod -aG docker "$(whoami)"
if ! command -v aws >/dev/null 2>&1; then
  curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
  unzip -q /tmp/awscliv2.zip -d /tmp/awscli
  sudo /tmp/awscli/aws/install
fi

log "ECR login (Node IAM role)"
aws ecr get-login-password --region "$REGION" \
  | sudo docker login --username AWS --password-stdin "${REGISTRY%%/*}"

if [ "$NODE_TIER" = "tier1" ]; then
  log "Installing RKE2 server (control plane)"
  if [ -n "$RKE2_TOKEN" ]; then
    # Pre-pin the cluster token so GPU workers (Terraform) can share one secret.
    sudo mkdir -p /etc/rancher/rke2
    printf 'token: %s\n' "$RKE2_TOKEN" | sudo tee /etc/rancher/rke2/config.yaml >/dev/null
  fi
  curl -sfL https://get.rke2.io | sudo sh -
  sudo systemctl enable rke2-server
  sudo systemctl start rke2-server
  until sudo /var/lib/rancher/rke2/bin/kubectl get nodes >/dev/null 2>&1; do sleep 3; done

  export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
  export PATH="/var/lib/rancher/rke2/bin:${PATH}"
  RKE2_TOKEN="$(sudo cat /var/lib/rancher/rke2/server/node-token)"

  log "Installing Helm"
  curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  chmod 700 /tmp/get_helm.sh; /tmp/get_helm.sh

  log "Cloning the rack repo (needed for Helm values + deploy)"
  if [ ! -d "$RACK_DIR" ]; then
    sudo git clone "$GIT_REPO" "$RACK_DIR"
  fi
  sudo chown -R "$(whoami)" "$RACK_DIR" || true

  log "Helm repos"
  helm repo add nvidia https://nvidia.github.io/gpu-operator >/dev/null 2>&1 || true
  helm repo add argo https://argoproj.github.io/argo-helm >/dev/null 2>&1 || true
  helm repo update >/dev/null 2>&1 || true

  log "Installing NVIDIA GPU Operator (drivers + device plugin)"
  helm install gpu-operator nvidia/gpu-operator -n gpu-operator --create-namespace \
    -f "$RACK_DIR/kubernetes/gpu-operator-values.yaml" || \
  helm upgrade --install gpu-operator nvidia/gpu-operator -n gpu-operator --create-namespace \
    -f "$RACK_DIR/kubernetes/gpu-operator-values.yaml"

  log "Installing Argo Workflows"
  helm install argo argo/argo-workflows -n argo --create-namespace \
    --set server.serviceType=ClusterIP \
    --set controller.workflowNamespaces={default,argo} || true
  kubectl -n argo rollout status deployment/argo-workflows-server --timeout=180s || true

  log "Labeling control plane"
  kubectl label node "$(hostname | tr 'A-Z' 'a-z')" cogniforge.rack/tier=tier1 \
    cogniforge.rack/role=control-plane --overwrite || true

else
  log "Joining as GPU worker ($NODE_TIER)"
  sudo mkdir -p /etc/rancher/rke2
  [ -n "$RKE2_TOKEN" ] || { echo "RKE2_TOKEN required for GPU workers" >&2; exit 1; }
  printf 'server: https://%s:9345\ntoken: %s\n' \
    "${RKE2_SERVER:-}" "$RKE2_TOKEN" | sudo tee /etc/rancher/rke2/config.yaml >/dev/null
  curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sudo sh -
  sudo systemctl enable rke2-agent; sudo systemctl start rke2-agent

  log "Waiting for node + GPU (may take a while for driver install)"
  export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
  export PATH="/var/lib/rancher/rke2/bin:${PATH}"
  until kubectl get nodes -o name | grep -qi "$(hostname)"; do sleep 3; done
  kubectl -n gpu-operator rollout status daemonset/gpu-operator --timeout=600s || true

  log "Labeling node tier"
  kubectl label node "$(hostname | tr 'A-Z' 'a-z')" \
    cogniforge.rack/tier="${NODE_TIER}" --overwrite || true
fi

if [ "$NODE_TIER" = "tier1" ]; then
  log "Cloning the rack repo"
  if [ ! -d "$RACK_DIR" ]; then
    sudo git clone "$GIT_REPO" "$RACK_DIR"
  fi
  sudo chown -R "$(whoami)" "$RACK_DIR" || true

  log "Deploying rack stack"
  cd "$RACK_DIR"
  export KUBECONFIG="${KUBECONFIG:-/etc/rancher/rke2/rke2.yaml}"
  export REGISTRY="$REGISTRY" IMAGE_TAG="$IMAGE_TAG"
  export RACK_ENGINE_URL="$RACK_ENGINE_URL"
  sudo -E ./scripts/deploy-cluster.sh || true
fi

log "Done. Node ${NODE_TIER} ready."
kubectl get nodes -o wide 2>/dev/null | head -n 5 || true